### ISSUE TITLE
Bug: reconnectIntervalを指定しないとWebSocketのエラーを吐く

### ISSUE THREAD

**Issue by mattyatea** [Allianaab2m/tsmi#11]
下記のエラーが出て起動できません
```
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: WebSocket was closed before the connection was established
    at WebSocket.close (C:\Users\mattyatea\WebstormProjects\mattyatea_kun\node_modules\.pnpm\ws@8.13.0\node_modules\ws\lib\websocket.js:285:7)
    at Timeout._onTimeout (C:\Users\mattyatea\WebstormProjects\mattyatea_kun\node_modules\.pnpm\tsmi@0.4.1\node_modules\tsmi\dist\websocket.js:63:19)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (C:\Users\mattyatea\WebstormProjects\mattyatea_kun\node_modules\.pnpm\ws@8.13.0\node_modules\ws\lib\websocket.js:1008:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

```

**Comment by Allianaab2m** [comment]
#13 で修正予定
